config/routes.rb
Atgdb::Application.routes.draw do
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users

  resources :managers do
    resource :ratings
  end
  resources :players do
    resource :ratings
  end
  resources :teams do
    resource :ratings
  end
  
  root :to => "teams#index"

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :players, :through => :teams
  has_many :ratings, :as => :rateable
  validates_presence_of :first_name, :message => "can't be blank"
  validates_presence_of :last_name, :message => "can't be blank"
  validates_uniqueness_of :last_name, :message => "must be unique", :scope => :first_name
  
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def rating # mean rating
    ratings.collect(&:rating_value).sum.to_f / ratings.size
  end
  
  def weighted_rating
    if rating > 0
      ((rating * ratings.size + Rating.mean * MINIMUM_NUMBER_OF_RATINGS) / (ratings.size + MINIMUM_NUMBER_OF_RATINGS)).round(1)
    else
      0
    end
  end 
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  # GET /managers
  # GET /managers.xml
  def index
    @managers = Manager.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.xml
  def show
    @manager = Manager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.xml
  def new
    @manager = Manager.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
  end

  # POST /managers
  # POST /managers.xml
  def create
    @manager = Manager.new(params[:manager])

    respond_to do |format|
      if @manager.save
        format.html { redirect_to(@manager, :notice => 'Manager was successfully created.') }
        format.xml  { render :xml => @manager, :status => :created, :location => @manager }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.xml
  def update
    @manager = Manager.find(params[:id])

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to(@manager, :notice => 'Manager was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.xml
  def destroy
    @manager = Manager.find(params[:id])
    @manager.destroy

    respond_to do |format|
      format.html { redirect_to(managers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= semantic_form_for @manager do |form| %>
<% if @manager.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

    <ul>
    <% @manager.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

    <%= form.inputs do %>
			<%= form.input :first_name %>
			<%= form.input :last_name %>
			<%= form.input :teams, :label => "Teams", :label_method => :label %>
    	<%= form.input :content %>
			<%= form.buttons %>
		<% end %>  
<% end %>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<h2>Listing managers</h2>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @managers.sort_by(&:weighted_rating).reverse.each do |manager| %>
  	<tr>
    	<td><%= manager.first_name %></td>
	    <td><%= manager.last_name %></td>
		<td>
		<% unless manager.ratings.blank? %>
			<%= manager.weighted_rating %>
		<% end %>
	    </td>
	    <td><%= link_to 'Show', manager %></td>
		<% if current_user %>
	    	<td><%= link_to 'Edit', edit_manager_path(manager) %></td>
	    	<td><%= link_to 'Destroy', manager, :confirm => 'Are you sure?', :method => :delete %></td>
  		<% end %>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="entry-options">
	<% if current_user %>
		<%= link_to 'Edit', edit_manager_path(@manager) %> |
	<% end %>
	<%= link_to 'Back', managers_path %>
</div>
<div id="managers" class="parent-show">
	<h1><%= @manager.first_name %>  <%= @manager.last_name %></h1>
	<div id="manager-rating">
		<div id="rating-values">
			<img src="/images/rating_new_bg.png" />																	
		</div>
		<span class="rating">
				<% unless @manager.ratings.blank? %>
				<%= @manager.weighted_rating %>
	  		<% end %>
		</span>	
	</div>
	<div id="manager-content">
		<%= @manager.content %>
	</div>
</div>
<div id="associations">
	<div class="child-show">
		<h2>Teams</h2>
		<ul>
		<% if @manager.teams.any? %>
			<% @manager.teams.each do |team| %>
				<li class="player"><%= link_to team %></li>
			<% end %>
		<% end %>
		</ul>
	</div>
</div>

<%= render 'ratings/new', :rateable => @manager %>