config/routes.rb
Atgdb::Application.routes.draw do
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users

  resources :managers do
    resource :ratings
  end
  resources :players do
    resource :ratings
  end
  resources :teams do
    resource :ratings
  end
  
  root :to => "teams#index"

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :managers, :through => :teams
  has_many :ratings, :as => :rateable
  validates_presence_of :last_name, :message => "can't be blank"
 
  def name
    "#{first_name} #{last_name}"
  end
  

  def rating # mean rating
    ratings.collect(&:rating_value).sum.to_f / ratings.size
  end
  
  def weighted_rating
    if rating > 0
      ((rating * ratings.size + Rating.mean * MINIMUM_NUMBER_OF_RATINGS) / (ratings.size + MINIMUM_NUMBER_OF_RATINGS)).round(1)
    else
      0
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  respond_to :html, :xml
  
  def index
    @players = Player.all
    respond_with(@players)
  end

  def show
    @player = Player.find(params[:id])
    respond_with(@player)
  end


  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(params[:player])
    if @player.save
      flash[:notice] = 'Player created successfully'
    end
    respond_with(@player)
  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(params[:player])
      flash[:notice => 'Player was successfully updated.']
    end
    respond_with(@player)
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    respond_with(@player)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= semantic_form_for @player do |form| %>
<% if @player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

    <%= form.inputs do %>
			<%= form.input :first_name %>
			<%= form.input :last_name %>
			<%= form.input :position %>
			<%= form.input :teams, :label => "Teams", :label_method => :label %>
    	<%= form.input :content %>
			<%= form.buttons %>
		<% end %>  
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h2>Listing players</h2>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Position</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.sort_by(&:weighted_rating).reverse.each do |player| %>
  	<tr>
    	<td><%= player.first_name %></td>
	    <td><%= player.last_name %></td>
	    <td><%= player.position %></td>
		<td>
		<% unless player.ratings.blank? %>
			<%= player.weighted_rating %>
		<% end %>
	    </td>
		<td><%= link_to 'Show', player %></td>
		<% if current_user %>
	    	<td><%= link_to 'Edit', edit_player_path(player) %></td>
		    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  		<% end %>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<div class="entry-options">
	<% if current_user %>
		<%= link_to 'Edit', edit_player_path(@player) %> |
	<% end %>
	<%= link_to 'Back', players_path %>
</div>
<div id="players" class="parent-show">
	<h1><%= @player.first_name %>  <%= @player.last_name %></h1>
	<div id="player-rating">
		<div id="rating-values">
			<img src="/images/rating_new_bg.png" />																	
		</div>
		<span class="rating">
				<% unless @player.ratings.blank? %>
				<%= @player.weighted_rating %>
	  		<% end %>
		</span>	
	</div>
	<div id="details">
		<strong>Position:</strong>
	  <%= @player.position %>
	</div>
	<div id="player-content">
		<%= @player.content %>
	</div>
</div>
<div id="associations">
	<div class="child-show">
		<h2>Teams</h2>
		<ul>
		<% if @player.teams.any? %>
			<% @player.teams.each do |team| %>
				<li class="player"><%= link_to team %></li>
			<% end %>
		<% end %>
		</ul>
	</div>
</div>

<%= render 'ratings/new', :rateable => @player %>