config/routes.rb
Atgdb::Application.routes.draw do
  resources :user_sessions
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  resources :users

  resources :managers do
    resource :ratings
  end
  resources :players do
    resource :ratings
  end
  resources :teams do
    resource :ratings
  end
  
  root :to => "teams#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atgdb</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
		<div id="header">
			<div class="container">
				<img src="/images/logo.png" id="logo" />
				<div id="navigation">
					<ul>
						<li><%= link_to("Players", :players) %></li>
						<li><%= link_to("Managers", :managers) %></li>
						<li><%= link_to("Teams", :teams) %></li>
					</ul>
				</div>
				<div id="user_nav">
				  <% if current_user %>
				    <%= link_to "View Profile", current_user %> |
				    <%= link_to "Logout", logout_path %>
				  <% else %>
				    <%= link_to "Register", new_user_path %> |
				    <%= link_to "Login", login_path %>
				  <% end %>
				</div>			
			</div>
		</div>
		<div id="content">
			<div class="container">
					<div class="content-nudge">
						<%= yield %>
					</div>
					<footer id="footer">
						<a href="#">footer link</a>
					</footer>					
			</div>
			<div id="social-media">
				<ul>
					<li><a href="#"><img src="/images/facebook.png" alt="Facebook" /></a></li>
					<li><a href="#"><img src="/images/twitter-2.png" alt="Twitter" /></a></li>
					<li><a href="#"><img src="/images/stumbleupon.png" alt="Stumble Upon" /></a></li>
					<li><a href="#"><img src="/images/delicious.png" alt="Delicious" /></a></li>
				</ul>
			</div>
		</div>
</body>
</html>